server:
  port: 8083
app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/ehrbridgecm
    username: postgres
    password: mysecretpassword
    pool-size: 30

callback-url: http://localhost:8083/api/v1/consent/notify-status